### ISSUE TITLE
I have an Error. Please Help

### ISSUE THREAD

**Issue by zywshuai** [burma69/PM3UniversalGUI#1]
TmpProcess.Start();

System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=系统找不到指定的文件。
  Source=System
  StackTrace:
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start()
   在 PM3UniversalGUI.PM3Client.<LoadCommands>d__8.MoveNext() 在 E:\PM3\PM3\PM3UniversalGUI-master\PM3UniversalGUI\PM3Client.cs 中: 第 575 行

**Comment by burma69** [comment]
Do you have proxmark3.exe in the same folder with the GUI? If no, then, please, make sure that PM3UniversalGui.exe.config file references a valid file in the following line:

<add key="PM3ClientFilename" value="C:\[your folder path here]\proxmark3.exe" />
